# Changes to a .dmm or anything in the _map subfolder
'🗺 Маппинг 🗺':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmm'
    - '_maps/**'

'🚀 Корабли 🚀':
- changed-files:
  - any-glob-to-any-file:
    - '_maps/shuttles/**'
    - '_maps/configs/**'
    - '_maps/_mod_celadon/shuttles/**'
    - '_maps/_mod_celadon/configs/**'

'🏔 Руинки 🏔':
- changed-files:
  - any-glob-to-any-file:
    - '_maps/RandomRuins/**'
    - 'code/datums/ruins/**'
    - '_maps/_mod_celadon/RandomRuins/**'

# Any .dmi changes
'🎨 Спрайты 🎨':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dmi'

# Any changes if not in modulare folder
'🪓 ТРОГАЛИ CORE-CODE 🪓':
- changed-files:
  - any-glob-to-any-file:
    - '_maps/map_files/**'
    - '_maps/shuttles/**'
    - 'code/**'
    - 'icons/**'
    - 'sound/**'

# Any sounds changes
'🔊 Звуки 🔊':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.aif'
    - '**/*.aiff'
    - '**/*.it'
    - '**/*.mid'
    - '**/*.midi'
    - '**/*.mod'
    - '**/*.mp3'
    - '**/*.ogg'
    - '**/*.oxm'
    - '**/*.raw'
    - '**/*.s3m'
    - '**/*.wma'
    - '**/*.wav'
    - '**/*.xm'

# Changes to the SQL subfolder
'📚 SQL 📚':
- changed-files:
  - any-glob-to-any-file:
    - 'SQL/**'

# Changes to the tgui subfolder
'💬 TGUI':
- changed-files:
  - any-glob-to-any-file:
    - 'tgui/**'

# Changes to the config subfolder
'🔮 Конфиги 🔮':
- changed-files:
  - any-glob-to-any-file:
    - 'config/**/*'
    - 'config/example/**/*'

# Changes to a .dm or anything in the code subfolder
'🧱 Код 🧱':
- changed-files:
  - any-glob-to-any-file:
    - '**/*.dm'

# Changes to the .Github subfolder
'🏭 Github 🏭':
- changed-files:
  - any-glob-to-any-file:
    - '.github/**'
    - '.github/**/*'
    - '.vscode/**/*'
    - 'docs/**/*'
    - 'scripts/**/*'
    - 'test/**/*'
    - 'tools/**/*'
    - '.codebeatignore'
    - '.codebeatsettings'
    - '.editorconfig'
    - '.git*'
    - 'biome.json'
    - 'libmysql.dll'
    - 'LICENSE'
    - 'README.md'
    - 'SpacemanDMM.toml'

# If anyone wants to update the Russian localization tools or wiki
'🏴‍☠️ Локализация 🏴‍☠️':
- changed-files:
  - any-glob-to-any-file:
    - 'code/__DEFINES/~mod_celadon/translation.dm'
    - '.github/TRANSLATION.md'

